backend:
  name: github
  repo: mertm01/freelance-portfolyo # Buraya kendi GitHub adını ve repo adını yaz
  branch: main # veya master

media_folder: "images" # Yüklenen resimlerin kaydedileceği klasör
public_folder: "/images"

collections:
  - name: "projeler"
    label: "Projeler / Son İşlerim"
    folder: "content/projeler" # İçeriklerin kaydedileceği klasör
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Proje Adı", name: "title", widget: "string"}
      - {label: "Kategori (Örn: Web Geliştirme)", name: "category", widget: "string"}
      - {label: "Kullanılan Teknolojiler (Virgülle ayırın)", name: "tech", widget: "string"}
      - {label: "Proje Görseli", name: "image", widget: "image"}